# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313dcfdb6b3ec74a9b8e077a635e2189db3bb80e5cdc42124436bed094c0056d12c7267e122def807aa13cd450527ea040a1f4062838da51d9e5f6235cdc772b

test:
  secret_key_base: 92b54dc9ee16a10c0df576af95558bf837a80539f1c5909c419dc9a6a6b775268386d7d65e3eb147e45a5ae4ef74d5afec5e30f6225580e5ceb3870e65a05e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
